namespace: samdoran
name: dev
version: 1.0.0
readme: README.md
authors:
  - Sam Doran <github@samdoran.com>

description: Roles and plugins for setting up a development workstation

license:
  - Apache-2.0

tags:
  - development
  - system
  - macos
  - xcode
  - python

dependencies: {}

repository: http://github.com/samdoran/ansible-collection-dev
documentation: http://github.com/samdoran/ansible-collection-dev/README.md
homepage: http://github.com/samdoran/ansible-collection-dev
issues: http://github.com/samdoran/ansible-collection-dev/issues

build_ignore: []
