- name: Create download directory
  file:
    path: "{{ nvidia_driver_download_dir }}"
    owner: root
    group: root
    state: directory
    mode: '0755'
  tags:
    - nvidia

- name: Download drivers
  get_url:
    url: "{{ nvidia_driver_url }}"
    dest: "{{ nvidia_driver_download_dir }}"
    owner: root
    group: root
    mode: '0755'
  register: nvidia_download
  tags:
    - nvidia

- name: Run installer
  shell: >-
    {{ nvidia_download.dest }}
    --ui=none
    --accept-license
    {{ nvidia_driver_extra_args | default("") }}
  args:
    chdir: "{{ nvidia_driver_download_dir }}"
  notify:
    - rebuild initramfs
    - make grub2 config
  tags:
    - nvidia

- name: Run sanity check
  shell: >-
    {{ nvidia_download.dest }}
    --ui=none
    --sanity
  args:
    chdir: "{{ nvidia_driver_download_dir }}"
  tags:
    - nvidia

- name: Find grub2 cfg
  find:
    paths: /boot/
    recurse: yes
    file_type: file
    patterns: grub.cfg
  register: grub2_cfg
  tags:
    - nvidia
    - nvidia_modprobe

- name: Disable nouveau driver
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    create: yes
    line: "{{ item.line | default(item) }}"
    state: "{{ item.state | default(omit) }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - blacklist nouveau
  notify:
    - rebuild initramfs
    - make grub2 config
  tags:
    - nvidia
    - nvidia_modprobe
