galaxy_info:
  role_name: google_cloud_sdk
  author: Sam Doran
  description: Install Google Cloud SDK
  license: Apache 2.0
  min_ansible_version: 2.11

  platforms:
  - name: macOS
    versions:
      - all

  galaxy_tags:
    - development
    - system
    - macos
    - xcode
